http:
  middlewares:
    cors:
      headers:
        accessControlAllowOriginList:
          - "http://localhost:4200"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "*"
        accessControlAllowCredentials: true
